### ISSUE TITLE
Add in-game browser option

### ISSUE THREAD

**Issue by Dianliang233** [mc-wiki/minecraft-mod-heywiki#10]
It's pretty evident from feedback on [Twitter](https://twitter.com/BluePotatoBP/status/1774182569656889709) that people want this.

Implementation can be https://github.com/CinemaMod/mcef. My little hacky idea is to make a https://tauri.app/ that lays over the game.

**Comment by thecathe** [comment]
I have also been looking to see if this is a possibility! I would really appreciate this feature.
Even though I have the mc-wiki mod installed I end up not using it since the muscle memory of alt+tab beats remembering how to use this mod.

There is also [MCBrowser (GitHub)](https://github.com/Blobanium/MCBrowser) [(modrinth)](https://modrinth.com/mod/mcbrowser) which is what I tried to use with this mod, to no avail.

Regarding the Steam Overlay Integration: is this a possibility? It wouldnt be ideal but I'd would also like to know if this is even an option.

**Comment by Dianliang233** [comment]
> Regarding the Steam Overlay Integration: is this a possibility? It wouldnt be ideal but I'd would also like to know if this is even an option.

someone suggested that it's possible to use an appid of a common steam game which everyone has, but i think it sounds sketchy.

I recently helped mcbrowser & mcef update to 1.21 and i'll try to add integration soon:tm:
